# Generated by Django 4.1.7 on 2023-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="phone_name",
            new_name="phone_number",
        ),
    ]
